# using sudo enabled linux VM
sudo: enabled
# Install the apt prerequisites
addons:
  apt:
    packages:
      - python-pygments
cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"
# Clean and don't fail
install:
  - wget https://github.com/spf13/hugo/releases/download/v0.26/hugo_0.26_Linux-64bit.deb
  - sudo dpkg -i hugo_0.26_Linux-64bit.deb
  - rm -rf public || exit 0
# Deploy to GitHub pages
script: bash ./deploy.sh
