# == GUJARATI ==

[Languages.gj]
  languageCode  = "gj"  # 2-letter code of language (ISO 639-1)
  languageName  = "Gujarati"  # verbose name of language (e.g. "Français" or "Русский")
  description   = "પબ્લિક મની, પબ્લિક કોડ - ફ્રી એન્ડ ઓપન સોર્સ સૉફ્ટવેર તરીકે સાર્વજનિક રૂપે ફાઇનાન્સ સૉફ્ટવેર રિલીઝ કરવા માટે ફોસ્સેઆમ ઝુંબેશ"
  fsdefinition  = "ફ્રી અને ઓપન સોર્સ સૉફ્ટવેર દરેકને સૉફ્ટવેરનો ઉપયોગ, અભ્યાસ, શેર અને બહેતર બનાવવાનો અધિકાર આપે છે."


# Navigation
[Languages.gj.navigation]
[Languages.gj.navigation.links]
  start     = "શરૂઆત"
  about     = "વિશે"
  arguments = "કારણો"
  action    = "પગલાં લેવા"
  spread    = "સમાચાર કે કોઈ વાત ને બહુ બધા લોકો સાથે ફેલાવવું"


# Start banner
[Languages.gj.start]
  subtitle1   = "ફ્રી અને ઓપન સોર્સ સૉફ્ટવેર તરીકે રિલીઝ થયેલા કરદાતાઓના મની દ્વારા સૉફ્ટવેર શા માટે બનાવવામાં આવ્યું છે?"
  subtitle2   = "અમે ઇચ્છતા હોઈએ છીએ કે જાહેર ક્ષેત્ર માટે વિકસિત જાહેર નાણાંકીય સૉફ્ટવેરને [ફ્રી અને ઓપન સોર્સ સૉફ્ટવેર] (https://en.wikipedia.org/wiki/Free_and_open-source_software) લાઇસેન્સ હેઠળ સાર્વજનિક રૂપે ઉપલબ્ધ કરાવવું જોઈએ. જો તે સાર્વજનિક નાણાં છે, તો તે સાર્વજનિક કોડ પણ હોવો જોઈએ. [સમગ્ર વિશ્વમાં] (https://publiccode.asia) પગલે, અમે જાહેર જનતા દ્વારા ચૂકવવામાં આવેલો કોડ પ્રકાશન માટે કૉલ કરવા માટે એક પહેલ શરૂ કરી રહ્યા છીએ."
  subtitle3   = "**લોકો દ્વારા આપવામાં આવેલ કોડ લોકો માટે ઉપલબ્ધ હોવો જોઈએ!**"


# About section
[Languages.gj.about]
  headline    = "જટિલ લાગે છે? તે નથી. તે સુપર સરળ છે!"
  buttonText  = "વધુ ફાયદા"


# Arguments section
[Languages.gj.arguments]
  headline    = "જાહેર કોડના કારણો"
  followup    = "શું તમે માનો છો કે મુક્ત અને ઓપન સોર્સ સૉફ્ટવેર જાહેરમાં ફાઇનાન્સ સૉફ્ટવેર માટે ડિફોલ્ટ વિકલ્પ હોવા જોઈએ? **ચાલો તમારા રાજકીય પ્રતિનિધિઓને સહમત કરીએ!**"
  buttonText  = "ઓપન પહેલ સાઇન ઇન કરો"
[[Languages.gj.arguments.list]]
  icon        = "fa-usd"  # <-- do not translate this
  title       = "કર બચત"
  description = "સમાન એપ્લિકેશન્સને દરેક વખતે શરૂઆતથી પ્રોગ્રામ કરવાની જરૂર નથી."
[[Languages.gj.arguments.list]]
  icon        = "fa-handshake-o"  # <-- do not translate this
  title       = "સહકાર"
  description = "મુખ્ય પ્રોજેક્ટ્સ પર પ્રયત્નો કુશળતા અને ખર્ચ શેર કરી શકે છે"
[[Languages.gj.arguments.list]]
  icon        = "fa-users"  # <-- do not translate this
  title       = "જાહેર સેવા આપતા"
  description = "લોકો દ્વારા ચૂકવવામાં આવતી એપ્લિકેશન્સ દરેક જણ માટે ઉપલબ્ધ હોવી જોઈએ."
[[Languages.gj.arguments.list]]
  icon        = "fa-lightbulb-o"  # <-- do not translate this
  title       = "નવીનતા ઉત્તેજન"
  description = "પારદર્શક પ્રક્રિયાઓ સાથે, અન્યને વ્હીલને પુનઃશોધવાની જરૂર નથી."


# Action section
[Languages.gj.action]
  headline      = "તમારા પ્રતિનિધિઓને કહો!"
  intro         = "અમારી [**ઓપન પહેલ**](openinitiative/) માં અમે માગણી કરીએ છીએ:"
  # In "demand", please use curly quotation marks for the demand. Otherwise the build might fail: https://en.wikipedia.org/wiki/Quotation_mark
  demand        = "“પબ્લિક સેક્ટર માટે વિકસાવવામાં આવતી સાર્વજનિક ફાયનાન્સ સોફ્ટવેરની આવશ્યકતા કાયદો લાગુ કરવી [ફ્રી અને ઓપન સોર્સ સૉફ્ટવેર] (https://en.wikipedia.org/wiki/Free_and_open-source_software) લાઇસેંસ હેઠળ જાહેરમાં ઉપલબ્ધ કરાવવી.”"
  description   = "**$ORGS** સંગઠનો અને **$INDS** વ્યક્તિઓ પહેલેથી જ અમારી [ઓપન પહેલ] (openinitiative/) પર સહી કરીને ક્રિયા માટે આ કોલને સમર્થન આપે છે. તમે તેના પર હસ્તાક્ષર કરીને અમને ઘણી મોટી અસરમાં મદદ કરી શકો છો! અમે બધા હસ્તાક્ષરોની સૂચિબદ્ધ કરીશું અને એશિયામાં પ્રતિનિધિઓને તેના હાથમાં સોંપીશું જે જાહેર વહીવટમાં સૉફ્ટવેરની નીતિઓ અંગે ચર્ચા કરે છે."


[Languages.gj.action.box]
  text      = "પહેલેથી **$INDS SIGNATURES** - હવે ઓપન પહેલ સાઇન ઇન કરો!"


[Languages.gj.action.form]
  name          = "નામ (જરૂરી)"
  email         = "ઇમેઇલ (જરૂરી)"
  country       = "તમારો દેશ"
  region        = "પ્રદેશ/શહેર"
  organization  = "સંસ્થા"
  comment       = "તમારી ટિપ્પણી (મહત્તમ 140 અક્ષરો)"
  permPriv      = "મેં [ગોપનીયતા વિધાન](privacy/) વાંચી અને સ્વીકારી છે"
  permNews      = "હું આ ઝુંબેશના ભાવિ વિશે માહિતગાર રહેવા માગું છું"
  permPub       = "હું [હસ્તાક્ષરોની સૂચિ](openinitiative/all-signatures) માં મારી હસ્તાક્ષરને દેખાવા માંગુ છું."
  submit        = "હમણાં સાઇન ઇન કરો!"


# Organisations section
[Languages.gj.organisations]
  headline  = "સહાયક સંસ્થાઓ"
  text      = "નીચેના સંસ્થાઓ અમારી [ઓપન પહેલ](openinitiative/). ને ટેકો આપે છે. જો તમારી સંસ્થા પબ્લીક કોડ માટે કૉલ કરવા માટે પણ રસ ધરાવે છે, તો કૃપા કરીને [અમારો સંપર્ક કરો](mailto:publiccode@fossasia.org)."


# Spread the word section
[Languages.gj.spread]
  headline          = "સમાચાર કે કોઈ વાત ને બહુ બધા લોકો સાથે ફેલાવવું!"
  promoText         = "FOSSASIA થી સ્ટીકરો અને ફ્લાયર્સ મેળવો"
  promoButtonText   = "માહિતી સામગ્રી ડાઉનલોડ કરો"
  shareText         = "સાર્વજનિક કોડ વિશે તમારા મિત્રો અને અનુયાયીઓને કહો:"
  defaultSocialText = "જો તે સાર્વજનિક નાણાં છે, તો તે સાર્વજનિક કોડ પણ હોવો જોઈએ. હું ફ્રી સૉફ્ટવેર લાઇસેંસ હેઠળ વધુ સાર્વજનિક કોડ માટે આ કૉલનું સમર્થન કરું છું:"


# Legal Section
[Languages.gj.legal]
  by            = "આ FOSSASIA દ્વારા ઝુંબેશ છે"
  imprint       = "છાપવું"
  privacy       = "ગોપનીયતા"
  transparency  = "પારદર્શિતા"
  contribute1   = "આ વેબસાઇટનું કોડ ફ્રી અને ઓપન સોર્સ સૉફ્ટવેર તરીકે લાઇસેંસ પ્રાપ્ત છે."
  contribute2   = "ફાળો આપવા માટે આપનું સ્વાગત છે!"
  license       = "આ કાર્ય તેના [ફાળો આપનારા](https://github.com/fossasia/publiccode.asia/contributors) દ્વારા [ક્રિએટિવ કૉમન્સ BY-SA 4.0 લાઇસેંસ](http://creativecommons.org/licenses/by-sa/4.0/) દ્વારા લાઇસેંસ પ્રાપ્ત છે"


# Language selection
[Languages.gj.language]
  description = "આ પૃષ્ઠને બીજી ભાષામાં વાંચો"


# 404 Error Page
[Languages.gj.error]
  headline    = "ભૂલ 404 - પૃષ્ઠ મળ્યું નથી"
  description = "તમે શોધી રહ્યાં છો તે પૃષ્ઠ અસ્તિત્વમાં નથી"
  button      = "પ્રારંભ પૃષ્ઠ પર પાછા ફરો"


# Specific sub-pages
[Languages.gj.subpage]
[Languages.gj.subpage.signatures]
  headline      = "વ્યક્તિગત ઓપન પહેલ સહીઓ"
  description   = "નીચે એવા સિગ્નેચરોનાં સહીઓ છે જેમણે તેમના નામો જાહેર કર્યા છે. આગામી એક બનો!"
  allSignatures = "[બધા જાહેર હસ્તાક્ષરો](all-signatures/) જુઓ."
  tableName     = "નામ"
  tableCountry  = "દેશ"
  tableComment  = "ટિપ્પણી કરો"
