# == TAMIL ==

## General strings
[Languages.tm]
  languageCode  = "tm"  # 2-letter code of language (ISO 639-1)
  languageName  = "தமிழ்"  # verbose name of language (e.g. "Français" or "Русский")
  description   = "பொது பணம், பொதுக் குறியீடு - பொது நிதியளித்த மென்பொருளை இலவச மற்றும் ஓப்பன் சோர்ஸ் மென்பொருளாக வெளியிட ஒரு FOSSASIA பிரச்சாரம்"
  fsdefinition  = "இலவச மற்றும் திறந்த மூல மென்பொருள் அனைவருக்கும் மென்பொருளை உபயோகிக்கவும், படிக்கவும், பகிர்ந்து கொள்ளவும், மேம்படுத்தவும் உரிமை அளிக்கிறது."


## Navigation
[Languages.tm.navigation]
[Languages.tm.navigation.links]
  start     = "தொடக்கம்"
  about     = "பற்றி"
  arguments = "காரணங்கள்"
  action    = "நடவடிக்கை எடு"
  spread    = "வார்த்தையை பரப்புங்கள்"

# Start banner
[Languages.tm.start]
  subtitle1   = "இலவச மற்றும் ஓபன் சோர்ஸ் மென்பொருளாக வெளியிடப்படாத வரி செலுத்துவோர் பணத்தைப் பயன்படுத்தி மென்பொருள் ஏன் உருவாக்கப்பட்டது?"
  subtitle2   = "பொதுத் துறைக்கு பகிரங்கமாக நிதியுதவி பெற்ற மென்பொருள், ஒரு [இலவச மற்றும் திறந்த மூல மென்பொருள்] (https://en.wikipedia.org/wiki/Free_and_open-source_software) உரிமத்தின் கீழ் பகிரங்கமாக வழங்கப்பட வேண்டும் என்று சட்டம் தேவை. பொதுமக்கள் பணமாக இருந்தால், அது பொதுக் குறியீடாகவும் இருக்க வேண்டும். [உலகம் முழுவதும்] (https://publiccode.asia) முன்முயற்சிகள் தொடர்ந்து, பொதுமக்களிடமிருந்து பெறப்படும் குறியீட்டை வெளியீடு செய்ய அழைக்க ஒரு முன்முயற்சியை நாங்கள் தொடங்குகிறோம்."
  subtitle3   = "**மக்களுக்கு வழங்கப்படும் கோட் மக்களுக்கு கிடைக்க வேண்டும்!**"

# About section
[Languages.tm.about]
  headline    = "சிக்கலான ஒலிகள்? அது இல்லை. இது சூப்பர் எளிது!"
  buttonText  = "மேலும் நன்மைகள்"

# Arguments section
[Languages.tm.arguments]
  headline    = "பொதுக் கோட்டிற்கான காரணங்கள்"
  followup    = "பொது மற்றும் நிதியளித்த மென்பொருளுக்கு இலவச மற்றும் திறந்த மூல மென்பொருள் இருக்க வேண்டும் என்று நீங்கள் நம்புகிறீர்களா? **உங்கள் அரசியல் பிரதிநிதிகளை நம்பவைக்கிறேன்!**"
  buttonText  = "திறந்த முயற்சியில் கையெழுத்திடுங்கள்"
[[Languages.tm.arguments.list]]
  icon        = "fa-usd"  # <-- do not translate this
  title       = "வரி சேமிப்பு"
  description = "இதே போன்ற பயன்பாடுகள் ஒவ்வொரு முறையும் ஒவ்வொரு முறையும் திட்டமிடப்பட வேண்டும்."
[[Languages.tm.arguments.list]]
  icon        = "fa-handshake-o"  # <-- do not translate this
  title       = "இணைந்து"
  description = "முக்கிய திட்டங்களில் முயற்சிகள் நிபுணத்துவம் மற்றும் செலவுகளை பகிர்ந்து கொள்ளலாம்."
[[Languages.tm.arguments.list]]
  icon        = "fa-users"  # <-- do not translate this
  title       = "பொது மக்களுக்கு சேவை செய்தல்"
  description = "பொது மக்களுக்கு சேவை செய்தல்..."
[[Languages.tm.arguments.list]]
  icon        = "fa-lightbulb-o"  # <-- do not translate this
  title       = "கண்டுபிடிப்புகளை வளர்ப்பது"
  description = "வெளிப்படையான செயல்முறைகளால், மற்றவர்கள் சக்கரத்தை புதிதாக்குவது இல்லை."

# Action section
[Languages.tm.action]
  headline      = "உங்கள் பிரதிநிதிகளுக்கு சொல்லுங்கள்!"
  intro         = "எங்கள் [**திறந்த முன்முயற்சியில்**](openinitiative/)நாங்கள் கோருகிறோம்:"
  # In "demand", please use curly quotation marks for the demand. Otherwise the build might fail: https://en.wikipedia.org/wiki/Quotation_mark
  demand        = "“பொதுத் துறைக்கு பகிரங்கமாக நிதியளிக்கப்பட்ட மென்பொருள் ஒரு [இலவச மற்றும் திறந்த மூல மென்பொருள்] (https://en.wikipedia.org/wiki/Free_and_open-source_software) உரிமத்தின் கீழ் பகிரப்படப்பட வேண்டும் என்று சட்டத்தை அமல்படுத்துதல்.”"
  description   = "**$ORGS** நிறுவனங்கள் மற்றும் **$INDS** தனிநபர்கள் ஏற்கனவே எங்கள் [திறந்த முன்முயற்சியை](openinitiative/)கையொப்பமிடுவதன் மூலம் நடவடிக்கைக்கு இந்த அழைப்பை ஆதரிக்கின்றனர்.அதை கையெழுத்து மூலம் ஒரு மிக பெரிய தாக்கத்தை எங்களுக்கு உதவ முடியும்! அனைத்து கையெழுத்துக்களையையும் பட்டியலிட்டு, பொது நிர்வாகத்தில் மென்பொருள் கொள்கைகளை விவாதிக்கும் ஆசியாவைச் சேர்ந்த பிரதிநிதிகளிடம் கையெழுத்திடுவோம்."

[Languages.tm.action.box]
  text      = "ஏற்கனவே **$INDS SIGNATURES** - இப்போது திறந்த முயற்சியை கையெழுத்திட!"

[Languages.tm.action.form]
  name          = "பெயர் (தேவை)"
  email         = "மின்னஞ்சல் (தேவை)"
  country       = "உங்கள் நாடு"
  region        = "வட்டாரம்/நகரம்"
  organization  = "அமைப்பு"
  comment       = "தங்கள் கருத்து (அதிகபட்சம் 140 எழுத்துகள்)"
  permPriv      = "நான் [தனியுரிமை அறிக்கை](privacy/)"
  permNews      = "இந்த பிரச்சாரத்தின் எதிர்காலத்தைப் பற்றி நான் தெரிவிக்க விரும்புகிறேன்"
  permPub       = "என் கையொப்பம் [கையொப்பங்களின் பட்டியல்](openinitiative/all-signatures)"
  submit        = "இப்போது உள்நுழைக!"

# Organisations section
[Languages.tm.organisations]
  headline  = "துணை நிறுவனங்கள்"
  text      = "பின்வரும் அமைப்புகள் எங்கள் [திறந்த முன்முயற்சியை ஆதரிக்கின்றன](openinitiative/). பொதுக் கோட்டிற்கான அழைப்பில் சேர உங்கள் ஆர்வமும் ஆர்வமாக இருந்தால், தயவுசெய்து [எங்களை தொடர்பு கொள்ளவும்](mailto:publiccode@fossasia.org)."


# Spread the word section
[Languages.tm.spread]
  headline          = "வார்த்தை பரவியது!"
  promoText         = "FOSSASIA இலிருந்து ஸ்டிக்கர்கள் மற்றும் ஃபிளையர்கள் கிடைக்கும்"
  promoButtonText   = "தகவல் பொருள் பதிவிறக்க"
  shareText         = "பொதுக் கோட் பற்றி உங்கள் நண்பர்களுக்கும் பின்பற்றுபவர்களுக்கும் சொல்லுங்கள்:"
  defaultSocialText = "பொதுமக்கள் பணமாக இருந்தால், அது பொதுக் குறியீடாகவும் இருக்க வேண்டும். ஒரு இலவச மென்பொருள் உரிமத்தின் கீழ் பொதுக் குறியீடுக்கு இந்த அழைப்பை ஆதரிக்கிறேன்:"

# Legal Section
[Languages.tm.legal]
  by            = "இது FOSSASIA இன் பிரச்சாரமாகும்"
  imprint       = "அடித்தளங்களை"
  privacy       = "தனியுரிமை"
  transparency  = "வெளிப்படைத்தன்மை"
  contribute1   = "இந்த வலைத்தளத்தின் குறியீடு இலவச மற்றும் திறந்த மூல மென்பொருள் உரிமம்."
  contribute2   = "பங்களிக்க நீங்கள் வரவேற்கப்படுகிறீர்கள்!"
  license       = "இந்த வேலை அதன் [பங்களிப்பாளர்கள்](https://github.com/fossasia/publiccode.asia/contributors) [கிரியேட்டிவ் காமன்ஸ் BY-SA 4.0 உரிமத்தின் கீழ்](http://creativecommons.org/licenses/by-sa/4.0/)."

# Language selection
[Languages.tm.language]
  description = "இந்தப் பக்கத்தை மற்றொரு மொழியில் படிக்கவும்"


# 404 Error Page
[Languages.tm.error]
  headline    = "பிழை 404 - பக்கம் காணப்படவில்லை"
  description = "நீங்கள் தேடும் பக்கம் இல்லை."
  button      = "பக்கத்தைத் தொடங்க மீண்டும்"


# Specific sub-pages
[Languages.tm.subpage]
[Languages.tm.subpage.signatures]
  headline      = "தனிப்பட்ட ஓபன் சம்மந்தப்பட்ட கையொப்பங்கள்"
  description   = "தங்கள் பெயர்களை பொதுமக்களிடம் கொண்டுவர ஒப்புக்கொண்ட கையெழுத்துக்களின் கையெழுத்துக்கள் கீழே கொடுக்கப்பட்டுள்ளன. அடுத்ததாக இருங்கள்!"
  allSignatures = "பார்க்க [அனைத்து பொது கையொப்பங்களும்](all-signatures/)."
  tableName     = "பெயர்"
  tableCountry  = "நாடு"
  tableComment  = "கருத்து"
