# == HINDI ==

## General strings
[Languages.hi]
  languageCode  = "hi"  # 2-letter code of language (ISO 639-1)
  languageName  = "हिंदी"  # verbose name of language (e.g. "Français" or "Русский")
  description   = "पब्लिक मनी, पब्लिक कोड - फ्री एंड ओपन सोर्स सॉफ़्टवेयर के रूप में सार्वजनिक रूप से वित्तपोषित सॉफ़्टवेयर को जारी करने के लिए एक फोसासिया अभियान"
  fsdefinition  = "निशुल्क और ओपन सोर्स सॉफ़्टवेयर हर किसी को सॉफ्टवेयर का इस्तेमाल, अध्ययन, साझा करने और सुधारने का अधिकार देता है।"


# Navigation
[Languages.hi.navigation]
[Languages.hi.navigation.links]
  start     = "आरंभ"
  about     = "के विषय में"
  arguments = "कारणों"
  action    = "कार्रवाई करें"
  spread    = "प्रचार कीजिये"


# Start banner
[Languages.hi.start]
  subtitle1   = "फ्री एंड ओपन सोर्स सॉफ़्टवेयर के रूप में रिलीज़ नहीं किए गए करदाताओं के पैसे का उपयोग कर सॉफ्टवेयर क्यों बनाया गया है?"
  subtitle2   = "हम चाहते हैं कि कानून चाहते हैं कि सार्वजनिक क्षेत्र के लिए विकसित सार्वजनिक रूप से वित्तपोषित सॉफ्टवेयर को [फ्री एंड ओपन सोर्स सॉफ्टवेयर] (https://en.wikipedia.org/wiki/Free_and_open-source_software) लाइसेंस के तहत सार्वजनिक रूप से उपलब्ध कराया जाए। अगर यह सार्वजनिक धन है, तो यह सार्वजनिक कोड भी होना चाहिए। [ग्लोब भर में] (https://publiccode.eu) निम्नलिखित पहल, हम जनता द्वारा भुगतान किए गए कोड के रिलीज के लिए कॉल करने के लिए एक पहल शुरू कर रहे हैं।"
  subtitle3   = "**लोगों द्वारा प्रदत्त कोड लोगों के लिए उपलब्ध होना चाहिए!**"


# About section
[Languages.hi.about]
  headline    = "जटिल लगता है? ऐसा नहीं है। यह सुपर आसान है!"
  buttonText  = "अधिक लाभ"


# Arguments section
[Languages.hi.arguments]
  headline    = "सार्वजनिक संहिता के लिए कारण"
  followup    = "क्या आप मानते हैं कि सार्वजनिक रूप से वित्तपोषित सॉफ़्टवेयर के लिए निशुल्क और ओपन सोर्स सॉफ़्टवेयर डिफ़ॉल्ट विकल्प होना चाहिए? ** चलो अपने राजनीतिक प्रतिनिधियों को मनाने! **"
  buttonText  = "खुले पहल पर हस्ताक्षर करें"
[[Languages.hi.arguments.list]]
  icon        = "fa-usd"  # <-- do not translate this
  title       = "टैक्स बचत"
  description = "समान अनुप्रयोगों को हर बार खरोंच से क्रमादेशित नहीं करना पड़ता है"
[[Languages.hi.arguments.list]]
  icon        = "fa-handshake-o"  # <-- do not translate this
  title       = "सहयोग"
  description = "प्रमुख परियोजनाओं पर प्रयास विशेषज्ञता और लागतों को साझा कर सकते हैं"
[[Languages.hi.arguments.list]]
  icon        = "fa-users"  # <-- do not translate this
  title       = "जनता की सेवा"
  description = "जनता द्वारा प्रदत्त आवेदन सभी के लिए उपलब्ध होना चाहिए।"
[[Languages.hi.arguments.list]]
  icon        = "fa-lightbulb-o"  # <-- do not translate this
  title       = "नवाचार को बढ़ावा देना"
  description = "पारदर्शी प्रक्रियाओं के साथ, अन्य को पहिया को फिर से बदलने की ज़रूरत नहीं है"


# Action section
[Languages.hi.action]
  headline      = "अपने प्रतिनिधियों को बताओ!"
  intro         = "हमारी [ खुली पहल ] (openinitiative/) में हम मांग करते हैं:"
  # In "demand", please use curly quotation marks for the demand. Otherwise the build might fail: https://en.wikipedia.org/wiki/Quotation_mark
  demand        = "“सार्वजनिक क्षेत्र के लिए विकसित सार्वजनिक रूप से वित्तपोषित सॉफ़्टवेयर को [फ्री एंड ओपन सोर्स सॉफ़्टवेयर] (https://en.wikipedia.org/wiki/Free_and_open-source_software) लाइसेंस के तहत सार्वजनिक रूप से उपलब्ध कराया जाना आवश्यक कानून लागू करें।”"
  description   = "**$ORGS** संगठनों और **$INDS** व्यक्ति पहले से ही हमारी [खुली पहल](openinitiative/) पर हस्ताक्षर करके इस कॉल के लिए समर्थन का समर्थन करते हैं। आप इसे हस्ताक्षर करके भी बहुत बड़ा प्रभाव बनाने में हमारी मदद कर सकते हैं! हम सभी हस्ताक्षरकर्ताओं को सूचीबद्ध करेंगे और एशिया में सभी प्रतिनिधियों के लिए इसे सौंपेंगे जो सार्वजनिक प्रशासन में सॉफ्टवेयर नीतियां बहस कर रहे हैं।"

[Languages.hi.action.box]
  text      = "पहले से ही **$INDS SIGNATURES** - अभी खुली पहल पर हस्ताक्षर करें!"

[Languages.hi.action.form]
  name          = "नाम (जरूरी)"
  email         = "ईमेल (अनिवार्य)"
  country       = "तुम्हारा देश"
  region        = "क्षेत्र/शहर"
  organization  = "संगठन"
  comment       = "आपकी टिप्पणी (अधिकतम 140 वर्ण)"
  permPriv      = "मैंने [गोपनीयता कथन](privacy/) को पढ़ लिया है और स्वीकार कर लिया है"
  permNews      = "मैं इस अभियान के भविष्य के बारे में सूचित रहना चाहता हूं"
  permPub       = "मैं चाहता हूं कि मेरे हस्ताक्षर [हस्ताक्षरों की सूची](openinitiative/all-signatures) में दिखें।"
  submit        = "अभी प्रवेश करें!"


# Organisations section
[Languages.hi.organisations]
  headline  = "सहायक संगठन"
  text      = "निम्नलिखित संगठन हमारी [खुली पहल] (openinitiative/) का समर्थन करते हैं। यदि आपका संगठन सार्वजनिक संहिता के लिए कॉल में शामिल होने में रुचि रखता है, तो कृपया [हमसे संपर्क करें] (mailto: publiccode@fossasia.org)।"


# Spread the word section
[Languages.hi.spread]
  headline          = "प्रचार कीजिये!"
  promoText         = "स्टॉकर्स और यात्रियों को FOSSASIA से प्राप्त करें"
  promoButtonText   = "डाउनलोड जानकारी सामग्री"
  shareText         = "सार्वजनिक संहिता के बारे में अपने मित्रों और अनुयायियों को बताएं:"
  defaultSocialText = "अगर यह सार्वजनिक धन है, तो यह सार्वजनिक कोड भी होना चाहिए। मैं एक फ्री सॉफ्टवेयर लाइसेंस के तहत अधिक सार्वजनिक कोड के लिए इस कॉल का समर्थन करता हूं:"


# Legal Section
[Languages.hi.legal]
  by            = "यह FOSSASIA द्वारा एक अभियान है"
  imprint       = "छाप"
  privacy       = "एकांत"
  transparency  = "पारदर्शिता"
  contribute1   = "इस वेबसाइट का कोड फ्री और ओपन सोर्स सॉफ़्टवेयर के रूप में लाइसेंस प्राप्त है।"
  contribute2   = "योगदान करने के लिए आपका स्वागत है!"
  license       = "यह काम एक [क्रिएटिव कॉमन्स BY-SA 4.0 लाइसेंस](http://creativecommons.org/licenses/by-sa/4.0/)।"


# Language selection
[Languages.hi.language]
  description = "इस पृष्ठ को अन्य भाषा में पढ़ें"



# 404 Error Page
[Languages.hi.error]
  headline    = "त्रुटि 404 - पृष्ठ नहीं मिला"
  description = "आप जो पृष्ठ ढूंढ रहे हैं वह मौजूद नहीं है"
  button      = "वापस पृष्ठ प्रारंभ करने के लिए"


# Specific sub-pages
[Languages.hi.subpage]
[Languages.hi.subpage.signatures]
  headline      = "व्यक्तिगत खुली पहल हस्ताक्षर"
  description   = "नीचे हस्ताक्षरकर्ताओं के हस्ताक्षर हैं जो उनके नाम सार्वजनिक करने पर सहमत हुए हैं। अगले एक रहो!"
  allSignatures = "[सभी सार्वजनिक हस्ताक्षर]](all-signatures/) देखें।"
  tableName     = "नाम"
  tableCountry  = "देश"
  tableComment  = "टिप्पणी"
