# == TELUGU ==

## General strings
[Languages.tl]
  languageCode  = "tl"  # 2-letter code of language (ISO 639-1)
  languageName  = "తెలుగు"  # verbose name of language (e.g. "Français" or "Русский")
  description   = "పబ్లిక్ మనీ, పబ్లిక్ కోడ్ - బహిరంగంగా ఆర్ధిక సాఫ్ట్వేర్ను ఉచితంగా మరియు ఓపెన్ సోర్స్ సాఫ్ట్వేర్గా విడుదల చేయడానికి ఒక FOSSASIA ప్రచారం"
  fsdefinition  = "ఉచిత మరియు ఓపెన్ సోర్స్ సాఫ్ట్వేర్ అందరికీ సాఫ్ట్వేర్ను ఉపయోగించడానికి, అధ్యయనం చేయడానికి, భాగస్వామ్యం చేయడానికి మరియు మెరుగుపరచడానికి హక్కు ఇస్తుంది."


# Navigation
[Languages.tl.navigation]
[Languages.tl.navigation.links]
  start     = "ప్రారంభం"
  about     = "గురించి"
  arguments = "కారణాలు"
  action    = "చర్య తీస్కో"
  spread    = "ఈ మాటను విస్తరింపచేయు"

# Start banner
[Languages.tl.start]
  subtitle1   = "ఉచిత మరియు ఓపెన్ సోర్స్ సాఫ్ట్వేర్ వలె విడుదల చేయని పన్ను చెల్లింపుదారుల డబ్బును సాఫ్ట్వేర్ ఎందుకు సృష్టించింది?"
  subtitle2   = "పబ్లిక్ సెక్టార్ కోసం బహిరంగంగా అభివృద్ధి చేసిన సాఫ్ట్ వేర్ ఒక [ఉచిత మరియు ఓపెన్ సోర్స్ సాఫ్ట్వేర్](https://en.wikipedia.org/wiki/Free_and_open-source_software) లైసెన్స్ ద్వారా బహిరంగంగా అందుబాటులో ఉంచాలని చట్టాల అవసరం మాకు అవసరం. ఇది పబ్లిక్ డబ్బు ఉంటే, అది పబ్లిక్ కోడ్ అయి ఉండాలి. [ప్రపంచవ్యాప్తంగా](https://publiccode.eu) చొరవలను అనుసరిస్తూ, ప్రజల ద్వారా చెల్లించిన కోడ్ విడుదల కోసం మేము ఒక చొరవ ప్రారంభించాము."
  subtitle3   = "**ప్రజలు చెల్లించే కోడ్ ప్రజలకు అందుబాటులో ఉండాలి!**"

# About section
[Languages.tl.about]
  headline    = "సంక్లిష్టమైన ధ్వనులు? ఇది కాదు. ఇది సూపర్ సులభం!"
  buttonText  = "మరింత ప్రయోజనాలు"

# Arguments section
[Languages.tl.arguments]
  headline    = "పబ్లిక్ కోడ్ కోసం కారణాలు"
  followup    = "బహిరంగంగా ఆర్ధిక సాఫ్ట్వేర్ కోసం ఉచిత మరియు ఓపెన్ సోర్స్ సాఫ్ట్వేర్ డిఫాల్ట్ ఎంపికగా ఉండాలని మీరు నమ్ముతున్నారా? **మీ రాజకీయ ప్రతినిధులను ఒప్పిద్దాం!**"
  buttonText  = "ఓపెన్ ఇనిషియేటివ్ సైన్ ఇన్ చేయండి"
[[Languages.tl.arguments.list]]
  icon        = "fa-usd"  # <-- do not translate this
  title       = "పన్ను పొదుపులు"
  description = "ప్రత్యామ్నాయ అనువర్తనాలు ప్రతిసారీ స్క్రాచ్ నుండి ప్రోగ్రామ్ చేయవలసిన అవసరం లేదు."
[[Languages.tl.arguments.list]]
  icon        = "fa-handshake-o"  # <-- do not translate this
  title       = "సహకారం"
  description = "ప్రధాన ప్రాజెక్టులపై చేసిన ప్రయత్నాలు నైపుణ్యం మరియు వ్యయాలను పంచుకోవచ్చు."
[[Languages.tl.arguments.list]]
  icon        = "fa-users"  # <-- do not translate this
  title       = "పబ్లిక్ అందిస్తోంది"
  description = "ప్రజలకు చెల్లించిన దరఖాస్తులు ప్రతి ఒక్కరికీ అందుబాటులో ఉండాలి."
[[Languages.tl.arguments.list]]
  icon        = "fa-lightbulb-o"  # <-- do not translate this
  title       = "ఆవిష్కరణ వృద్ధి"
  description = "పారదర్శక ప్రక్రియలతో, ఇతరులు చక్రం ఆవిష్కరణ లేదు."

# Action section
[Languages.tl.action]
  headline      = "మీ ప్రతినిధులకు చెప్పండి!"
  intro         = "మా [**ఓపెన్ చొరవ**](openinitiative/) లో మేము డిమాండ్ చేస్తున్నాము:"
  # In "demand", please use curly quotation marks for the demand. Otherwise the build might fail: https://en.wikipedia.org/wiki/Quotation_mark
  demand        = "“పబ్లిక్ సెక్టార్ కోసం బహిరంగంగా అభివృద్ధి చేసిన సాఫ్ట్వేర్ను [ఫ్రీ అండ్ ఓపెన్ సోర్స్ సాఫ్ట్వేర్](https://en.wikipedia.org/wiki/Free_and_open-source_software) లైసెన్స్ ద్వారా బహిరంగంగా అందుబాటులో ఉంచాలని చట్టాలను అమలు చేయండి.”"
  description   = "**$ORGS** సంస్థలు మరియు **$INDS** మంది వ్యక్తులు మా [బహిరంగ కార్యక్రమంలో](openinitiative/) సంతకం చేయడం ద్వారా చర్య కోసం ఇప్పటికే ఈ కాల్కి మద్దతు ఇస్తున్నారు. సంతకం చేయడం ద్వారా మాకు చాలా ఎక్కువ ప్రభావం చూపడానికి మీకు సహాయం చేయవచ్చు! మేము అన్ని సంతకాలు జాబితా మరియు ప్రజా పరిపాలన లో సాఫ్ట్వేర్ విధానాలు చర్చించడం ఆ ఆసియా అంతటా ప్రతినిధులకు అప్పగించండి ఉంటుంది."

[Languages.tl.action.box]
  text      = "ఇప్పటికే **$INDS SIGNATURES** - ఓపెన్ చొరవ ఇప్పుడు సైన్ ఇన్!"

[Languages.tl.action.form]
  name          = "పేరు (అవసరం)"
  email         = "ఇమెయిల్ (అవసరం)"
  country       = "మీ దేశం"
  region        = "ప్రాంతం / సిటీ"
  organization  = "సంస్థ"
  comment       = "మీ వ్యాఖ్య (గరిష్టంగా 140 అక్షరాలు)"
  permPriv      = "నేను [గోప్య ప్రకటన](privacy/) ను చదివాను మరియు అంగీకరించాను"
  permNews      = "నేను ఈ ప్రచారం యొక్క భవిష్యత్తు గురించి తెలియజేయాలనుకుంటున్నాను"
  permPub       = "నా సంతకం [సంతకం జాబితాలో](openinitiative/all-signatures)"
  submit        = "ఇప్పుడు సైన్ ఇన్ చేయండి!"

# Organisations section
[Languages.tl.organisations]
  headline  = "సహాయక సంస్థలు"
  text      = "కింది సంస్థలు మా [ఓపెన్ చొరవని](openinitiative/) మద్దతు ఇస్తుంది. మీ సంస్థ ప్రజా కోడ్ కోసం పిలుపులో చేరడానికి కూడా ఆసక్తి కలిగి ఉంటే, దయచేసి [మమ్మల్ని సంప్రదించండి](mailto:publiccode@fossasia.org)."


# Spread the word section
[Languages.tl.spread]
  headline          = "ఈ మాటను విస్తరింపచేయు!"
  promoText         = "ఈ మాటను విస్తరింపచేయు!..."
  promoButtonText   = "సమాచారం మెటీరియల్ డౌన్లోడ్"
  shareText         = "పబ్లిక్ కోడ్ గురించి మీ స్నేహితులకు మరియు అనుచరులకు చెప్పండి:"
  defaultSocialText = "ఇది పబ్లిక్ డబ్బు ఉంటే, అది పబ్లిక్ కోడ్ అయి ఉండాలి. నేను ఒక ఫ్రీ సాఫ్ట్వేర్ లైసెన్సు క్రింద మరింత ప్రజా కోడ్ కోసం ఈ కాల్కు మద్దతు ఇస్తున్నాను:"

# Legal Section
[Languages.tl.legal]
  by            = "ఇది FOSSASIA ద్వారా ప్రచారం"
  imprint       = "మనసులో దృఢమైన ముద్రవేయు"
  privacy       = "గోప్యతా"
  transparency  = "పారదర్శకత"
  contribute1   = "ఈ వెబ్సైట్ యొక్క కోడ్ ఉచిత మరియు ఓపెన్ సోర్స్ సాఫ్ట్వేర్ లైసెన్స్."
  contribute2   = "మీరు సహకరించడానికి స్వాగతం!"
  license       = "ఈ పని [క్రియేటివ్ కామన్స్ BY-SA 4.0 లైసెన్సు](https://github.com/fossasia/publiccode.asia/contributors) కింద [లైసెన్సుల](http://creativecommons.org/licenses/by-sa/4.0/)ద్వారా లైసెన్స్ చేయబడింది."

# Language selection
[Languages.tl.language]
  description = "మరొక పేజీలో ఈ పేజీని చదవండి"


# 404 Error Page
[Languages.tl.error]
  headline    = "లోపం 404 - పేజీ దొరకలేదు"
  description = "మీరు వెతుకుతున్న పేజీ లేదు."
  button      = "పేజీని ప్రారంభించడానికి వెనుకకు"


# Specific sub-pages
[Languages.tl.subpage]
[Languages.tl.subpage.signatures]
  headline      = "వ్యక్తిగత ఓపెన్ ఇనిషియేటివ్ సంతకాలు"
  description   = "క్రింద ఇవ్వబడిన సంతకం యొక్క సంతకాలు వారి పేర్లు బహిర్గతమయ్యాయి. తదుపరిది అవ్వండి!"
  allSignatures = "[అన్ని పబ్లిక్ సంతకాలను](all-signatures/) చూడండి."
  tableName     = "పేరు"
  tableCountry  = "దేశం"
  tableComment  = "వ్యాఖ్య"
